<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="72" started-at="2017-06-22T15:11:58Z" finished-at="2017-06-22T15:11:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="72" started-at="2017-06-22T15:11:58Z" finished-at="2017-06-22T15:11:58Z">
      <class name="tests.task0107.Tst0701SolvePos">
        <test-method status="FAIL" signature="f(double, double, double, java.util.ArrayList)[pri:0, instance:tests.task0107.Tst0701SolvePos@3c09711b]" name="f" duration-ms="49" started-at="2017-06-22T18:11:58Z" data-provider="dp" finished-at="2017-06-22T18:11:58Z">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
Data provider mismatch
Method: f([Parameter{index=0, type=double, declaredAnnotations=[]}, Parameter{index=1, type=double, declaredAnnotations=[]}, Parameter{index=2, type=double, declaredAnnotations=[]}, Parameter{index=3, type=java.util.ArrayList, declaredAnnotations=[]}])
Arguments: [(java.lang.Double)0.0,(java.lang.Double)2.0,(java.lang.Double)1.0,(java.util.Arrays$ArrayList)[[D@53b32d7, [D@5442a311, [D@548e7350]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: f([Parameter{index=0, type=double, declaredAnnotations=[]}, Parameter{index=1, type=double, declaredAnnotations=[]}, Parameter{index=2, type=double, declaredAnnotations=[]}, Parameter{index=3, type=java.util.ArrayList, declaredAnnotations=[]}])
Arguments: [(java.lang.Double)0.0,(java.lang.Double)2.0,(java.lang.Double)1.0,(java.util.Arrays$ArrayList)[[D@53b32d7, [D@5442a311, [D@548e7350]]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:49)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1187)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- tests.task0107.Tst0701SolvePos -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
