<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPBYMINW2705" name="tests.task0103.Tst0301Triangle" tests="18" failures="2" timestamp="26 Jun 2017 09:41:34 GMT" time="0.070" errors="0">
  <testcase name="triangleIllegalArgExpIncorrectValue" time="0.003" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="triangleIllegalArgExpIncorrectValue" time="0.003" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="triangleIllegalArgExpIncorrectValue" time="0.003" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="triangleIllegalArgExpIncorrectValue" time="0.003" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="getAreaValidValue" time="0.018" classname="tests.task0103.Tst0301Triangle">
    <failure type="java.lang.AssertionError" message="expected [0.5] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [0.5] but found [1.0]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at tests.task0103.Tst0301Triangle.getAreaValidValue(Tst0301Triangle.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- getAreaValidValue -->
  <testcase name="triangleIllegalArgExpIncorrectValue" time="0.001" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="getAreaValidValue" time="0.003" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="triangleIllegalArgExpIncorrectValue" time="0.002" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="triangleIllegalArgExpIncorrectValue" time="0.001" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="triangleIllegalArgExpValidValue" time="0.002" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="triangleIllegalArgExpValidValue" time="0.008" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="triangleIllegalArgExpIncorrectValue" time="0.002" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="getPerimeterValidValue" time="0.007" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="getPerimeterValidValue" time="0.003" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="getPerimeterValidValue" time="0.003" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="getPerimeterValidValue" time="0.001" classname="tests.task0103.Tst0301Triangle"/>
  <testcase name="getAreaValidValue" time="0.002" classname="tests.task0103.Tst0301Triangle">
    <failure type="java.lang.AssertionError" message="expected [6.0] but found [3.5]">
      <![CDATA[java.lang.AssertionError: expected [6.0] but found [3.5]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at tests.task0103.Tst0301Triangle.getAreaValidValue(Tst0301Triangle.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- getAreaValidValue -->
  <testcase name="triangleIllegalArgExpIncorrectValue" time="0.005" classname="tests.task0103.Tst0301Triangle"/>
</testsuite> <!-- tests.task0103.Tst0301Triangle -->
