<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Failed suite [TestSuite]">
  <test name="AutoQA(failed)">
    <classes>
      <class name="tests.task0102.Tst0201ExpressionResolve">
        <methods>
          <include name="checkResolveCatchArithmeticExpIncorrectValues" invocation-numbers="0 1 2 3"/>
          <include name="checkResolveCatchIllegalArgExpIncorrectValues" invocation-numbers="0 1 2 3"/>
        </methods>
      </class> <!-- tests.task0102.Tst0201ExpressionResolve -->
      <class name="tests.task0110.Tst1001Generate">
        <methods>
          <include name="catchingIllegalArgExceptionInegerMAXValue" invocation-numbers="0"/>
        </methods>
      </class> <!-- tests.task0110.Tst1001Generate -->
      <class name="tests.task0107.Tst0701Solve">
        <methods>
          <include name="f" invocation-numbers="0"/>
        </methods>
      </class> <!-- tests.task0107.Tst0701Solve -->
      <class name="tests.task0103.Tst0301Triangle">
        <methods>
          <include name="getAreaValidValue" invocation-numbers="0 2"/>
        </methods>
      </class> <!-- tests.task0103.Tst0301Triangle -->
      <class name="tests.task0108.Tst0801ArrayExceptionPos">
        <methods>
          <include name="arrayCorrectValues" invocation-numbers="1"/>
          <include name="divisionByZero" invocation-numbers="0"/>
          <include name="divisionByZeroCatchExp" invocation-numbers="0"/>
        </methods>
      </class> <!-- tests.task0108.Tst0801ArrayExceptionPos -->
    </classes>
  </test> <!-- AutoQA(failed) -->
</suite> <!-- Failed suite [TestSuite] -->
